### ISSUE TITLE
Count=0; but reads is detected

### ISSUE THREAD

**Issue by Niohuruzh** [htseq/htseq#77] opened 2024-01-18 09:32 UTC
Hi
When I use `htseq-count -f bam -i transcript_id -s reverse 1.bam 1.gtf > 1.count`. The results suggest that the count of A gene is equal to zero. But when I use IGV to check the bam file, I find there is a lot of reads mapping to A gene? So I want to know what happening in my raw data or code?

<img width="1773" alt="image" src="https://github.com/htseq/htseq/assets/82928607/cc15ce25-ec8f-40cf-afa5-8ca65070a4bd">

<img width="150" alt="image" src="https://github.com/htseq/htseq/assets/82928607/9ee854cc-2299-4a60-83d0-3584291358ff">

**Comment by iosonofabio** [comment] 2024-01-18 19:24
Thank you for reaching out.

Please provide a small complete example and not just images.

**Comment by Niohuruzh** [comment] 2024-01-19 01:24
Thanks for your reply.

I use the following code to get the bam file
`hisat2 -p 46 -x ./1_index/Fh99 --rna-strandness RF -1 ../0_archive/paired/${a}_R1.paired.fq.gz -2 ../0_archive/paired/${a}_R2.paired.fq.gz -S ./${a}.sam`
`samtools view -@ 46 -bS ./${a}.sam > ./${a}.bam`
`samtools sort -@ 46 ./${a}.bam -T ./${a}.sorted -o ./${a}.sorted.bam`
`samtools index ${a}.sorted.bam`
samtools 1.3.1

and then the following code to get the count file
`htseq-count -f bam -i transcript_id -s reverse ${a}.sorted.bam ../1_data/gtf/99.gtf > ./${a}.count`

and then the following code to get the TPM file
`stringtie -p 48 -e ${a}.sorted.bam -G ../1_data/gtf/99.gtf -o ./outfile${a}.gtf -A ./${a}.abundance -C ./${a}_ref.gtf`

I upload the `1.count `,`1.abundance` file and '99.gtf' file.
[file.zip](https://github.com/htseq/htseq/files/13983190/file.zip)

**Comment by Niohuruzh** [comment] 2024-01-19 02:20
How can I send you bam file. The file size too big to upload

**Comment by Niohuruzh** [comment] 2024-01-19 02:30
I have sent the bam file to your email

**Comment by iosonofabio** [comment] 2024-01-19 03:31
Thank you. That file is 400 MB. Unfortunately I don't have time to deal with huge files because the troubleshooting is really slow. Can you please create a small example that reproduces the bug, max 5MB for the BAM and 5MB for the GTF file?

**Comment by iosonofabio** [comment] 2024-01-19 03:59
I've seen your email. Please keep the discussion and files here on GitHub and don't move it to emails, they are difficult to track for others with similar bugs.

I've run your command on the example. There are 0 reads overlapping that transcript with the right strandedness. There is 1 read pair with the opposite strandedness, as it turns out, and htseq-count detects it correctly.

So it seems to work just fine. You might want to check the strandedness of your experimental protocol?

**Comment by Niohuruzh** [comment] 2024-01-19 04:03
Thanks for your help.

If the gene A is counted zero, why is the TPM has the value in `abundance` file.

**Comment by iosonofabio** [comment] 2024-01-19 04:05
I don't know since I'm not the stringtie developer.

Closing since it does not appear to be an HTSeq bug until evidence for the contrary. Feel free to reopen if you have reason to believe this is an HTSeq bug.

**Closed by iosonofabio** 2024-01-19 04:05 UTC

**Comment by Niohuruzh** [comment] 2024-01-19 08:54
Hi
Thanks for your help

However, I want to know why visualize the bam file in IGV, I found there are lots of reads mapped to gene A while its count value is zero.
<img width="1445" alt="image" src="https://github.com/htseq/htseq/assets/82928607/c0873cdf-9535-451a-8786-d37c75884b4b">

**Comment by iosonofabio** [comment] 2024-01-19 09:42
Strandedness? Secondary alignments? Hard to tell without more detail about the protocol

**Comment by iosonofabio** [comment] 2024-01-19 09:43
Btw we are not talking about reads but read pairs

**Comment by Niohuruzh** [comment] 2024-01-19 12:20
I test the bam file and the results show that "This is PairEnd data"
