### ISSUE TITLE
htseq-count-barcodes on long-read single cell data

### ISSUE THREAD

**Issue by anikajohn** [htseq/htseq#73] opened 2023-12-04 09:14 UTC
**Software versions**
Specify what versions of the following you are using:
- `HTSeq: 0.12.4`
- `Python: 3.8.16`
-  Linux
- `pbmm2: 1.13.1` 
- `GenomicFeatures: 1.50.4`

**Question**

Dear htseq team,

first of all thanks for providing this tool and the extensive documentation available online. It's amazing! I am not sure if what I am reporting is a true bug or just due to the fact that my data set is rather unique and hence I am also seeking out for some advice from your side.

My data set is long-read (PacBio) single cell RNA-seq. Analysis on the data has been done before and we are confident that the data is of sufficient quality regarding coverage per cell, sequencing quality etc.

**My goal is to generate an exon and intron count matrix.**  In the end the rows of this matrix should represent the genes and the columns the cell barcode, the entries should be the intron/exon counts. To this end I deployed your tool `htseq-count-barcodes` as follows.

`htseq-count-barcodes "$bam_path" "$ExonCoordinates" -i gene_id -i exonic_part --additional-attr gene_id --additional-attr exonic_part --stranded no --minaqual 0 --nonunique all > ./"${Ex_output_name}"`

`htseq-count-barcodes "$bam_path" "$IntronCoordinates" -i gene_id -i intronic_part --additional-attr gene_id -t intron --additional-attr intronic_part --stranded no --minaqual 0 --nonunique all > ./"${Int_output_name}"`

_Generating $ExonCoordinates and  $IntronCoordinates using R package **GenomicFeatures**_

```
library(GenomicFeatures)
library(rtracklayer)
library(GenomicDataCommons)

txdb <- makeTxDbFromGFF('sorted.gtf')

all.introns <- intronicParts(txdb, linked.to.single.gene.only=TRUE)
all.exons <- exonicParts(txdb, linked.to.single.gene.only=TRUE)

subset.introns <- all.introns[width(all.introns) > 5000]

names(all.exons) =
  sprintf("%s:E%0.3d", 
          all.exons$gene_id, 
          all.exons$exonic_part)

names(subset.introns) =
  sprintf("%s:E%0.3d", 
          subset.introns$gene_id, 
          subset.introns$intronic_part)

rtracklayer::export(all.exons, 'exons_flat.gtf')
rtracklayer::export(subset.introns, 'introns_flat.gtf')
```
(not shown: renaming third column of exons_flat.gtf and introns_flat.gtf')

The code runs through nicely and the output format is as expected. However once I collapse the individual exon/intron counts by gene, it is evident that the resulting matrix only contains a small fraction of genes (exon 15, intron 64) that were present in $ExonCoordinates and  $IntronCoordinates gtf files. In addition, when looking at the quality control output (summed over cell barcodes), I see that a lot of transcripts are classified as `__no_feature`. E.g. exon matrix:

`__no_feature: 2948272`
`__ambiguous: 6768`
`__too_low_aQual: 0`
`__not_aligned: 0`
`__alignment_not_unique: 0`

The chromosom annotations are the same in `sorted.gtf` and exon/intron coordinates. My bam files are sorted. At this point I am not sure what else could be causing this issue and would appreciate any advice.

**Comment by anikajohn** [comment] 2023-12-04 13:41
Dear @iosonofabio,

thank you for your fast reply. My data contains UMIs and we collapsed them using the isoeq workflow (https://isoseq.how/umi/cli-workflow.html). As my data is rather sensitive so I'll have to think about how or if I can share a reproducible example. So in case you already have some input or additional resources for me I would be happy to hear them :).

**Comment by anikajohn** [comment] 2023-12-06 10:30
Dear @iosonofabio,

I made a small example data set. As you see in the igv screen shot below there is some coverage of the exons that I defined (although not much). However when running `htseq-count-barcodes` as described above on this data, no count for any of the exons is recorded. 

![image](https://github.com/htseq/htseq/assets/62256170/bd41d25d-013c-4a10-b73a-c6c7cfd95971)
[sample.bam.bai.gz](https://github.com/htseq/htseq/files/13579842/sample.bam.bai.gz)
[sample.bam.gz](https://github.com/htseq/htseq/files/13579843/sample.bam.gz)
[exons_flat.gtf.gz](https://github.com/htseq/htseq/files/13579845/exons_flat.gtf.gz)
[introns_flat.gtf.gz](https://github.com/htseq/htseq/files/13579846/introns_flat.gtf.gz)
[ExonCount.txt.gz](https://github.com/htseq/htseq/files/13579849/ExonCount.txt.gz)
[IntronCount.txt.gz](https://github.com/htseq/htseq/files/13579851/IntronCount.txt.gz)

**Comment by iosonofabio** [comment] 2023-12-06 10:37
Thank you, I'll try to run it ASAP, might be next week I'm afraid. I'll keep you posted
Fabio

**Comment by anikajohn** [comment] 2023-12-06 12:03
Thank you, much appreciated!

**Comment by iosonofabio** [comment] 2024-01-12 01:12
Hi, apologies, baby + busy writing papers, I'm trying my best but can't give you an exact timeline yet

**Comment by iosonofabio** [comment] 2024-04-28 07:33
Hi @anikajohn, apologies about the late reply. I finally got time to test this.

I cannot reproduce, I actually get exonic counts from that example, as in the file attached, with the simple command:

```
htseq-count-barcodes sample.bam exons_flat.gtf -c exons.tsv
```

[exons.tsv.gz](https://github.com/htseq/htseq/files/15141194/exons.tsv.gz)

Are you sure you are using the latest version of HTSeq, 2.0.5?

**Comment by iosonofabio** [comment] 2024-07-07 05:31
@anikajohn hey, did you have a chance to confirm this? Since I cannot reproduce the erroneous behaviour, I'll close the issue for now, but feel free to reopen if you can confirm and provide some additional info, happy to help

**Closed by iosonofabio** 2024-07-07 05:31 UTC
