### ISSUE TITLE
Counts difference htseq-count version 0.13.5 and 1.99.2.

### ISSUE THREAD

**Issue by gerbenvoshol** [htseq/htseq#54] opened 2022-06-20 07:12 UTC
First of all thanks for developing HTSeq!

We were running a simple test to compare the output of htseq-count 2.0.1 and 0.11.0 and noticed some differences:

The older version (0.11.0) reported the following summary metrics:
__no_feature		12522350
__ambiguous		800482
__too_low_aQual		0
__not_aligned		0
__alignment_not_unique		640187

While the new version (2.0.1) reports:
__no_feature		6771128
__ambiguous		422058
__too_low_aQual		0
__not_aligned		11903020
__alignment_not_unique		348779

Also the counts are about half in the new version:
old (0.11.0) version:
ENSG00000288714.1	RP3-460G2.1	32
ENSG00000288715.1	GS2-740I5.1	0
ENSG00000288716.1	AC001226.8	0
ENSG00000288717.1	RP11-852E15.4	1
ENSG00000288718.1	RP11-509I21.4	0
ENSG00000288719.1	RP4-669P10.21	26
ENSG00000288720.1	RP11-852E15.3	1
ENSG00000288721.1	RP5-973N23.5	11
ENSG00000288722.1	F8A1	111
ENSG00000288723.1	RP11-553N16.6	0
ENSG00000288724.1	RP13-546I2.2	0
ENSG00000288725.1	RP11-413H22.3	0

new (2.0.1) version:
ENSG00000288714.1	RP3-460G2.1	18
ENSG00000288715.1	GS2-740I5.1	0
ENSG00000288716.1	AC001226.8	0
ENSG00000288717.1	RP11-852E15.4	1
ENSG00000288718.1	RP11-509I21.4	0
ENSG00000288719.1	RP4-669P10.21	14
ENSG00000288720.1	RP11-852E15.3	1
ENSG00000288721.1	RP5-973N23.5	7
ENSG00000288722.1	F8A1	56
ENSG00000288723.1	RP11-553N16.6	0
ENSG00000288724.1	RP13-546I2.2	0
ENSG00000288725.1	RP11-413H22.3	0

Note: Another counter (VERSE: https://github.com/gerbenvoshol/VERSE) matches the output of the older version, but was designed to match htseq-count (v 0.x) output

Both were run with the same parameters:
singularity run -B /mnt htseq-2.0.1.sif htseq-count -f bam -t exon -i gene_id --additional-attr gene_name --stranded=yes test.bam annotation.gtf >test.raw

Is there an option I should set? Or is there another explanation for these observations?

Thanks!

Singularity container htseq-count 0.11.0:
- HTSeq 0.11.0
- Python 3.6.7
- Ubuntu 18.04
- STAR 2.5.2

Singularity container htseq-count 2.0.1:
- HTSeq 0.11.0
- Python 3.10.4
- Ubuntu 22.04
- STAR 2.5.2

**Comment by iosonofabio** [comment] 2022-06-20 11:26
Default behavior for chimeric and multimapping reads had changed, could you please test the new version while varying the options related to that and take a look at the results?

If you'd like me to take a look myself please link a <5MB GTF file and a <5MB BAM file and your own results on it,  I'll give it a go

**Comment by gerbenvoshol** [comment] 2022-06-20 12:31
Thanks! Could you specify which options specifically to vary? The --help output looks  identical for secondary and supplementary alignments.

**Comment by gerbenvoshol** [comment] 2022-06-28 14:59
We tried varying some of the settings (e.g. supplementary reads), but the output of the old and new version still don't match. Since the paper makes no mention of a change in algorithm for the bulk RNAseq counting. Can you elaborate on what you mean with "Default behavior for chimeric and multimapping reads has changed"?

**Comment by gerbenvoshol** [comment] 2022-07-01 10:52
Hi, I made a subset from the original bam and gtf file and tested it with versoin 0.11.0, 0.13.5, 1.99.2 and 2.0.1. All older version have identical counts (<0.13.5) to version 0.11.0 and all newer match the output of 1.99.2 (and newer). I uploaded the test data to https://github.com/gerbenvoshol/htseq-count

**Comment by iosonofabio** [comment] 2022-07-01 16:29
Thank you.

Just to clarify: the way I understand your last message, the change happened between 0.11 and 0.13. is that correct?

Thank you for the test repo. The BAM file is >5MB. Could you please make a minimal BAM with size <5MB?

**Comment by gerbenvoshol** [comment] 2022-07-01 17:04
Hi, the change seems to have happened between version 0.13.5 and 1.99.2.

Next week I can have a look if I can reduce the file size of the SAM file from 84 MB to approximately 5 MB, while still maintaining some of the informational content.

**Comment by iosonofabio** [comment] 2022-07-01 17:20
Thank you.

Information does not matter, it's just about getting different counts so we can debug.

**Comment by iosonofabio** [comment] 2022-07-01 17:53
Converting the SAM file to BAM reduces it to ~8MB, good enough.

Turns out my postdoc refactored the code in 6166cc8 and introduced this bug. Since that's pretty much the only commit I didn't work on myself, it's double hard to track down but let me take a look.

**Comment by iosonofabio** [comment] 2022-07-01 18:37
This is a legit bug in the logic that happened in the relatively rare corner case in which read1 is often unmapped/missing but read2 is there.

The old logic is to trust read2 as the bearer of truth for the entire paired-end molecule, even though read1 got lost before HTSeq can see it. The new logic is to throw away the entire pair since read1 is missing.

The change happened by mistake, which is why it's not mentioned in the paper. I can see some point to it, but it should definitely not be implemented as a surprise for users, so for now I reverted back to the old behaviour in commit d9adc38dafadca1455ae73d68b752270e6188a9b.

If you need this urgently, please install the latest `master` branch from this repo. Otherwise, I'll push a new release one of the next days. At that time, I'll also close this issue.

Thanks again for reporting. Would it be okay to use your example files in the test suite to avoid future regressions?

**Comment by gerbenvoshol** [comment] 2022-07-02 05:58
Hi, thanks for your quick response and fix. We will wait for the official release, so we can validate the output and use it to replace the aging 0.11.0 version.

These example files are copyrighted by GenomeScan B.V., but think we can release them under a more permissive license. Which license do you suggest?

**Comment by iosonofabio** [comment] 2022-07-02 06:35
Released 2.0.2, closing. HTSeq is GPL3 so it cannot be used for commercial purposes anyway, we might as well stick to that.

**Closed by iosonofabio** 2022-07-02 06:35 UTC

**Comment by gerbenvoshol** [comment] 2022-07-02 10:53
Thanks, GPLv3 should be fine. Eventhough it might not make too much sense in this case, it makes the overall licensing terms of HTSeq more uniform.
